// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImCaOb7hdw51iR-kOfkzia65Uxs0HtZk',
    appId: '1:333405064207:web:1b3b32fc2e5daf94a2e77a',
    messagingSenderId: '333405064207',
    projectId: 'bus-project-36efc',
    authDomain: 'bus-project-36efc.firebaseapp.com',
    storageBucket: 'bus-project-36efc.firebasestorage.app',
    measurementId: 'G-CZ4LRCTL54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp-GzpkZbOoc9cqoFzx5ApxkmLvquGk7w',
    appId: '1:333405064207:android:a9868ae3f38cda4aa2e77a',
    messagingSenderId: '333405064207',
    projectId: 'bus-project-36efc',
    storageBucket: 'bus-project-36efc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImCaOb7hdw51iR-kOfkzia65Uxs0HtZk',
    appId: '1:333405064207:web:23a1e4f536a9a898a2e77a',
    messagingSenderId: '333405064207',
    projectId: 'bus-project-36efc',
    authDomain: 'bus-project-36efc.firebaseapp.com',
    storageBucket: 'bus-project-36efc.firebasestorage.app',
    measurementId: 'G-W0PX3L5RPZ',
  );
}
